/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeBridge */

#ifndef _Included_NativeBridge
#define _Included_NativeBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeBridge
 * Method:    testConnection
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_NativeBridge_testConnection(JNIEnv *, jobject);

/*
 * Class:     NativeBridge
 * Method:    seedDemoData
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeBridge_seedDemoData(JNIEnv *, jobject);

/*
 * Class:     NativeBridge
 * Method:    getShortestPath
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_NativeBridge_getShortestPath(JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     NativeBridge
 * Method:    navLocations
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_NativeBridge_navLocations(JNIEnv *, jobject);

/*
 * Class:     NativeBridge
 * Method:    navShortestPath
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_NativeBridge_navShortestPath(JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     NativeBridge
 * Method:    sisUpsertStudent
 * Signature: (ILjava/lang/String;Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_NativeBridge_sisUpsertStudent(JNIEnv *, jobject, jint, jstring, jstring, jint);

/*
 * Class:     NativeBridge
 * Method:    sisGetStudent
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_NativeBridge_sisGetStudent(JNIEnv *, jobject, jint);

/*
 * Class:     NativeBridge
 * Method:    sisDeleteStudent
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_NativeBridge_sisDeleteStudent(JNIEnv *, jobject, jint);

/*
 * Class:     NativeBridge
 * Method:    sisListStudents
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_NativeBridge_sisListStudents(JNIEnv *, jobject);

/*
 * Class:     NativeBridge
 * Method:    sisTreeSnapshot
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_NativeBridge_sisTreeSnapshot(JNIEnv *, jobject);

/*
 * Class:     NativeBridge
 * Method:    attRegisterStudent
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_NativeBridge_attRegisterStudent(JNIEnv *, jobject, jint, jstring);

/*
 * Class:     NativeBridge
 * Method:    attNewSessionDay
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_NativeBridge_attNewSessionDay(JNIEnv *, jobject);

/*
 * Class:     NativeBridge
 * Method:    attMarkPresent
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_NativeBridge_attMarkPresent(JNIEnv *, jobject, jint);

/*
 * Class:     NativeBridge
 * Method:    attGetSummary
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_NativeBridge_attGetSummary(JNIEnv *, jobject, jint);

/*
 * Class:     NativeBridge
 * Method:    attGetDefaulters
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_NativeBridge_attGetDefaulters(JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
