/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeBridge */

#ifndef _Included_NativeBridge
#define _Included_NativeBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeBridge
 * Method:    testConnection
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_NativeBridge_testConnection
  (JNIEnv *, jobject);

/*
 * Class:     NativeBridge
 * Method:    getShortestPath
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_NativeBridge_getShortestPath
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
